### ISSUE TITLE
consider a redirect from api.open.fec.gov

### ISSUE THREAD

**Issue by gbinal** [18F/openFEC#1048]
Less important than #1045, but would be a good thing to do if not hard:  

Set up a redirect from `api.open.fec.gov` to `api.open.fec.gov/developers`.  The former is something some folks will try and it's worth having it redirect instead of 404ing.

**Comment by jmcarp** [comment]
Resolved in #1042--just needs to be merged into master.

**Comment by konklone** [comment]
It's merged into master, but `https://api.open.fec.gov/` still doesn't redirect for me.

**Comment by jmcarp** [comment]
Thanks for keeping me honest @konklone. The fix got merged, but the auto-deploy through Travis failed, since master is still using the old stack on CF. Which reminds me that we need to get notifications on deployment success / failure.

Anyway, it's working on production now.

**Comment by konklone** [comment]
It totally is!

**Comment by LindsayYoung** [comment]
Thanks for fixing that, Josh!
