### ISSUE TITLE
Snowe records confusing

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC#1248]
We are having issues representing data Olympia Snowe

There are a few issues, 
 - Snowe doesn't show up in the 2012 election page, she filed a F2 did not run, I am not sure if this is expected behavior or not.
 - Snowe's financials don't show up for 11-12 on her candidate page. I think this is because her principal committee, changed types during the cycle.

**Comment by LindsayYoung** [comment]
I went down the wrong path earlier, this isn't a special election issue- I misremembered, she said she wouldn't run again, but didn't resign.

The 2011 entry was a filer error and later amended. I would have thought that the 2011 entry in dimcandoffice would have been expired.

**Comment by PaulClark2** [comment]
Currently Statements of Candidacy for a specific candidate are primarily grouped by reported election year.   An F2 amendment can only amend an F2 with the same election year.  An F2 amendment cannot change the election year of a previously filed F2.

**Comment by jmcarp** [comment]
As far as I can tell, this was resolved in #1278. We'll still likely want to tweak our candidate views to rely less on DW tables, as described in #1327, but I think this can be closed for now. @LindsayYoung can you confirm?

**Comment by LindsayYoung** [comment]
Her fundraising does not show up:
https://beta.fec.gov/data/candidate/S4ME00055/?cycle=2012

I think it is because her committee changed types during the cycle.

The other issue, it is still wrong that that table, but we don't use that table anymore

**Comment by LindsayYoung** [comment]
Fixed it works:
https://beta.fec.gov/data/candidate/S4ME00055/?cycle=2012

**Comment by LindsayYoung** [comment]
fixed
