### ISSUE TITLE
Fix update_all processing

### ISSUE THREAD

**Issue by ccostino** [18F/openFEC#2286]
Our `update_all` script is still not running at the moment and currently encountering two issues while processing:

* An execution error when attempting to run a subprocess, likely due to an unquoted/unescaped shell command.
* A database error: `sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column ofec_totals_house_senate_mv.last_debts_owed_to_committee does not exist`

These (and any other issues) need to be addressed ASAP so that we can properly refresh the new GovCloud database instances.

**Comment by noahmanger** [comment]
Is this resolved by #2288 ?

**Comment by ccostino** [comment]
Yes, but it's actually resolved by #2289 - we had merged it into the wrong branch initially, but fixed it almost immediately afterward (h/t @LindsayYoung for catching that!).

**Comment by ccostino** [comment]
It looks like the partitioning is still an issue, at the moment apparently due to an `unknown` column type, which is the case in both the `fec_vsum_sched_a_vw` and `fec_vsum_sched_b_vw` views (the `schedule_type`).  I had specifically tested and accounted for this in the partitioning code ([example here](https://github.com/18F/openFEC/blob/develop/webservices/partition/sched_a.py#L28)) with additional support for handling it, yet it continues to be an issue.

Furthermore, it is cropping up as an issue with the nightly updates when the schedule A and B queues are being processed.  We are seeing errors in those email notifications now too about being unable to handle a column with an `unknown` column type.

/cc @LindsayYoung

**Comment by ccostino** [comment]
I see one lingering issue - the [child table refresh method in the partition code](https://github.com/18F/openFEC/blob/develop/webservices/partition/base.py#L256) does not account for the recasting of the `schedule_type` column, thus leading to the error we're seeing thrown in the nightly refresh emails now for the GovCloud databases.  What I'm pretty sure is happening is it's grabbing the rows from the queue tables and trying to insert/remove them as is from the child table, which will fail because of the `schedule_type` column mismatch.

I confirmed the column type in the queue tables by looking at them in the DB.  Furthermore, the changes I recently made to support building the queue tables and populating them with row changes pulled via the corresponding views is why this is the case with them (e.g., [this row variable](https://github.com/18F/openFEC/blob/develop/data/sql_setup/prepare_schedule_a.sql#L27)).

We could potentially fix this by adjusting both the queue table creation code and the `insert` and `delete` statements to list out every column explicitly and recast it there, or possibly in the `refresh_child()` method in the partition code.  I am opting for the `refresh_child()` method at the moment as the support is already written on that side and I think it'll be quicker.

Regardless, I'll open another PR to capture this remaining work.

**Comment by ccostino** [comment]
I stand corrected, though the `refresh_child()` method is still likely an issue.  Another problem exists within `update_aggregates()`, and that is what we're actually seeing fail in our email notifications.  The calls and underlying code [starting here](https://github.com/18F/openFEC/blob/develop/data/functions/aggregates.sql#L4) are also unable to handle the `unknown` column type.

**Comment by ccostino** [comment]
This issue is finally resolved.  PR #2293 fixed the remaining nightly update issues and we've already integrated them into all of the GovCloud databases.  We've also been able to successfully run the partitioning again and have added a bit more flexibility to allow us to run the partitioning of schedule A and B separately and at the same time.  With the E/W environment going away, we do not have to worry about those instances anymore.
